import {presetPlan,quickSearchOptions,SEARCH_PRESETS} from '../../src/data/redisSearchPresets.js';
import {test} from 'node:test';
import {Readable} from 'node:stream';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {RedisPipeline} from './pipeline.js';
import {packBody} from './payload.js';
import {createUserSearch,searchSchemas,compilePlan,executeSearch,requestedContext,generatePlan,requireEnabledLayer} from './userSearch.js';
const base={query:'*',operation:'search',sortBy:'',sortDirection:'DESC',limit:1,groupBy:[],metrics:[],scope:'global',region:null,focus:true,explanation:'Test',clarification:null};
test('camera and selection are passed only for explicitly scoped requests',()=>{
 const context={viewport:{west:1},selected:{id:'a'}};
 assert.deepEqual(requestedContext('fastest satellite',context),{});
 assert.deepEqual(requestedContext('fastest satellite in this view',context),{viewport:context.viewport});
 assert.deepEqual(requestedContext('closest military flight to this',context),{selected:context.selected});
});
test('real Search sorts satellites; GEO aggregates speeds and nearest finds the correct aircraft',async()=>{
 const prefix=`gev-search-test:${randomUUID()}`,p=new RedisPipeline({prefix});const client=await p.connect();const cleanup=client.duplicate();cleanup.on('error',()=>{});await cleanup.connect();
 const pack=x=>packBody(Buffer.from(JSON.stringify(x)),'application/json');
 try{
  await p.project('flights','one',pack({states:[['a','ONE','Israel',1,1,34.8,32.1,1000,false,100],['b','TWO','Israel',1,1,35,32.2,1000,false,200],['c','THREE','France',1,1,2,48,1000,false,300]]}));
  await p.project('military','one',pack({ac:[{hex:'near',flight:'NEAR',lat:32.11,lon:34.81,gs:200},{hex:'far',flight:'FAR',lat:34,lon:36,gs:300}]}));
  await p.ensure('satellites');
  await client.sendCommand(['JSON.SET',`${prefix}:satellites:entity:records:fast`,'$',JSON.stringify({id:'fast',layer:'satellites',name:'STARLINK FAST',type:'COMMS · STARLINK',latitude:89,longitude:30,location:'30,89',speedMps:7800})]);
  await client.sendCommand(['JSON.SET',`${prefix}:satellites:entity:records:slow`,'$',JSON.stringify({id:'slow',layer:'satellites',name:'STARLINK SLOW',type:'COMMS · STARLINK',latitude:32,longitude:34,location:'34,32',speedMps:7400})]);
  await p.project('radio','one',pack({stations:[{stationuuid:'radio1',name:'News Radio',tags:'news,talk',geo_lat:32,geo_long:34}]}));
  await p.project('ais-live-vessels','one',pack({rows:[{mmsi:'123',name:'SUEZ TEST',lat:30.6,lon:32.35}]}));
  await p.project('local-datacenters','one',packBody(Buffer.from(JSON.stringify({id:'dc',type:'Feature',geometry:{type:'Point',coordinates:[34,32]},properties:{tags:{name:'Test DC',operator:'Example'}}})),'text/plain','/src/data/local_data/datacenters/datacenters.geojsonl'));
  const schemas=await searchSchemas(client,prefix);
  assert.deepEqual(schemas.find(s=>s.layer==='satellites').fields.find(f=>f.name==='type').topValues,[{value:'COMMS · STARLINK',count:2}]);
  assert.deepEqual(schemas.find(s=>s.layer==='radio').fields.find(f=>f.name==='tag').topValues,[{value:'news',count:1},{value:'talk',count:1}]);
  assert.throws(()=>requireEnabledLayer('satellites',[{id:'satellites',name:'Satellites',enabled:false}]),/Enable Satellites/);
  requireEnabledLayer('satellites',[{id:'satellites',enabled:true}]);
  const run=(layer,plan,context)=>executeSearch(client,compilePlan({...base,index:`${prefix}:${layer}:idx`,...plan},schemas,context));
  const handler=createUserSearch(p);
  const request=async(route,body)=>{
    const req=Readable.from([Buffer.from(JSON.stringify(body))]);req.method='POST';req.headers={};
    let status,payload;const res={writeHead(code){status=code;},end(text){payload=JSON.parse(text);}};
    await handler(route,req,res,new AbortController().signal);return {status,payload};
  };
  const layers=[{id:'flights',name:'Live Flights',enabled:true}];
  const planned=await request('/search/preset',{presetId:'tel-aviv-flights',layers});
  assert.equal(planned.status,200);assert.equal(planned.payload.command[0],'FT.AGGREGATE');
  const executed=await request('/search/run',{id:planned.payload.id,layers});
  assert.equal(Number(executed.payload.rows[0].count),2);
  const disabled=await request('/search/preset',{presetId:'tel-aviv-flights',layers:[{...layers[0],enabled:false}]});
  assert.equal(disabled.status,400);assert.match(disabled.payload.error,/Enable Live Flights/);
  const stopped=await request('/search/run',{id:planned.payload.id,layers:[]});
  assert.equal(stopped.status,400);
  const quick=async id=>executeSearch(client,compilePlan(presetPlan(id,prefix),schemas));
  for(const preset of SEARCH_PRESETS)await executeSearch(client,compilePlan(presetPlan(preset.id,prefix),schemas,{viewport:{west:20,east:40,south:20,north:40}}));
  assert.equal(Number((await quick('suez-vessels')).rows[0].count),1);
  assert.equal(Number((await quick('datacenter-operator-count')).rows[0].operators),1);
  assert.equal(Number((await quick('tel-aviv-flights')).rows[0].count),2);
  assert.equal(Number((await quick('starlink-speed')).rows[0].averageSpeedMps),7600);
  assert.equal((await quick('fastest-flight')).rows[0].id,'c');
  assert.throws(()=>presetPlan('FLUSHALL',prefix),/Unknown/);
  const quickSchemas=await searchSchemas(client,prefix,{layer:'flights',includeValues:false});
  assert.equal(quickSchemas.length,1);assert.equal(quickSchemas[0].layer,'flights');
  assert.ok(quickSchemas[0].fields.every(f=>!f.topValues));
  assert.equal(quickSearchOptions(null,[]).length,0);
  assert.deepEqual(quickSearchOptions({layer:'flights',latitude:32,longitude:34},[{id:'military',enabled:true},{id:'radio',enabled:false}]).slice(0,1).map(p=>p.id),['closest:military']);
  const fastest=await run('satellites',{query:'@type:(COMMS*)',sortBy:'speedMps'});
  assert.equal(fastest.rows[0].id,'fast');
  const aggregate=await run('flights',{operation:'aggregate',region:{name:'Israel',west:34,east:36,south:29,north:34},metrics:[{function:'AVG',field:'speedMps',alias:'averageSpeedMps'},{function:'COUNT',field:'',alias:'count'}]});
  assert.equal(Number(aggregate.rows[0].averageSpeedMps),150);assert.equal(Number(aggregate.rows[0].count),2);assert.match(aggregate.command[2],/@location:/);
  const nearest=await run('military',{operation:'nearest',scope:'selected'},{selected:{id:'a',layer:'flights',longitude:34.8,latitude:32.1}});
  assert.equal(nearest.rows[0].id,'near');assert.ok(nearest.rows[0].distanceM<2000);
  const other=await run('military',{operation:'nearest',scope:'selected'},{selected:{id:'near',layer:'military',longitude:34.81,latitude:32.11}});
  assert.equal(other.rows[0].id,'far','nearest excludes the selected object itself');
  const empty=await run('flights',{operation:'aggregate',query:'@label:(NOTTHERE)',metrics:[{function:'AVG',field:'speedMps',alias:'average'}]});
  assert.deepEqual(empty.rows,[],'missing measurements must not become a misleading average');
  assert.throws(()=>compilePlan({...base,index:`${prefix}:flights:idx`,operation:'FLUSHALL'},schemas),/Only Search/);
  assert.throws(()=>compilePlan({...base,index:`${prefix}:flights:idx`,query:'@secret:x'},schemas),/Unsupported indexed/);
  assert.throws(()=>compilePlan({...base,index:`${prefix}:flights:idx`,scope:'viewport'},schemas),/No viewport/);
  let sent;
  await generatePlan('fastest airplane',schemas,{viewport:{west:1}}, {call:async(path,body)=>{sent=JSON.parse(body.input);return {output:[{content:[{type:'output_text',text:JSON.stringify({...base,index:`${prefix}:flights:idx`,sortBy:'speedMps'})}]}]};}});
  assert.deepEqual(sent.context,{});
  await assert.rejects(generatePlan('fastest airplane',schemas,{}, {layers:[{id:'flights',name:'Live Flights',enabled:false}],call:async()=>({output:[{content:[{type:'output_text',text:JSON.stringify({...base,index:`${prefix}:flights:idx`})}]}]})}),/Enable Live Flights/);
  assert.throws(()=>compilePlan({...base,index:`${prefix}:cctv:idx`},schemas),/Enable the relevant data layer/);
 }finally{
  await p.close();for(const index of await cleanup.sendCommand(['FT._LIST']))if(index.startsWith(prefix+':'))await cleanup.sendCommand(['FT.DROPINDEX',index]);
  const keys=await cleanup.keys(prefix+':*');if(keys.length)await cleanup.unlink(keys);await cleanup.close();
 }
});
